@id=00000000-0000-000000000001

PUT http://localhost:5253/{{id}}
Content-Type: application/json

{
    "name": "V",
    "description": "",
    "startDateTime": "2022-04-08T08:00:00",
    "endDateTime": "2022-04-08T11:00:00",
    "savory": [
        "Oatmeal",
        "Avocado Toast ",
        "Omelette",
        "Salad"
    ],
    "Sweet": [
        "Cookie"
    ]
}